#permalink:    /:year/:month/:day/:title
#analytics_id: UA-19957147-1
title:        Contextual Studies
#description:  Personal website of Dave Lim
#url:          http://am.dlimiter.net
url:          http://0.0.0.0:4000
author:       Dave Lim
email:        dave@dlimiter.net
css_path:     /identity
# css_path:       
#twitter:      http://twitter.com/dlimiter
#github:       http://github.com/dlimiter
#dribbble:     http://dribbble.com/dlimiter
#linkedin:     http://au.linkedin.com/in/dlimiter
#zerply:       http://zerply.com/profile/dlimiter/public
#keywords:     design,development,software,illustration,css,html,ruby,rails,blog
#comments:     true
#feed:         http://feeds.feedburner.com/dlimiterdotnet
#ignore:       _blog, _posts/folio

#environment: production